### ISSUE TITLE
Screensaver issue - Only showing one image - GOOGLE API BROKEN

### ISSUE THREAD

**Issue by Erkroed** [chtaylo2/Roku-GooglePhotos#65]
The screensaver has started showing a single photo for all instances instead of multiple photos chosen from throughout my account. As recently as this weekend this was not the case. 

I have no idea how it picked the photo it did, either. It's a random photo from my account, but it's been the same one since I noticed the issue. Deleting and re-adding the channel did not fix the situation.

**Comment by chtaylo2** [comment]
Something happened with Google's API and they (Google) is not returning random images as of this weekend. It's a known issue, looking into.

**Comment by chtaylo2** [comment]
Closing issue. This has been fixed in Release 1.7 (https://github.com/chtaylo2/Roku-GooglePhotos/releases/tag/1.7)  Update has been pushed to Roku for publishing.

**Comment by lsiegrist** [comment]
I'm having what looks like a similar issue to the ones I just saw above. The roku app isn't working for screensaver. It only shows 2 cat pictures that aren't even from any of my albums that I can tell. Which is freaky. I just removed the channel and added it again and saw that it looked like it had been updated, but still didn't fix the issue. I've logged out and in a few times, restarted the roku itself. Nada. 
Can this be fixed? 
Thanks!

**Comment by chtaylo2** [comment]
@lsiegrist It's not been approved yet by Roku.  It'll update once Roku approves the publish.

**Comment by lsiegrist** [comment]
Awesome! Can't wait to get these creepy cat pictures off my screensaver 😂

**Comment by chtaylo2** [comment]
Closing issue. New version published

**Comment by Erkroed** [comment]
Update just rolled out, problem solved. Thanks
